version: '3.5'
services:
    web1:
        restart: on-failure
        build: ./backend
        hostname: web1
        env_file:
            - .env
        ports:
            - '81:8080'
        networks:
            - rede-teste
        volumes:
            - ./backend/app:/home/code/app
    web2:
        restart: on-failure
        build: ./backend
        hostname: web2
        env_file:
            - .env
        ports:
            - '82:8080'
        networks:
            - rede-teste
        volumes:
            - ./backend/app:/home/code/app
    mysql:
        image: company-database
        env_file:
            - .env
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        networks:
            - rede-teste
    nginx:
        build: ./nginx
        ports:
            - '80:80'
        depends_on:
            - web1
            - web2
        networks:
            - rede-teste
    phpmyadmin:
        image: phpmyadmin
        env_file:
            - .env
        ports: 
            - '8181:80'
        environment:
            PMA_HOST: ${PMA_HOST}
            PMA_PORT: ${PMA_PORT}
            PMA_USER: ${PMA_USER}
            PMA_PASSWORD: ${PMA_PASSWORD}
        depends_on:
            - mysql
        networks:
            - rede-teste
networks:
    rede-teste:
        driver: bridge